# Generated by Django 5.0.3 on 2025-06-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="taxable",
            field=models.BooleanField(
                default=True, help_text="Whether this product is taxable"
            ),
        ),
    ]
