# Generated by Django 5.0.3 on 2025-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_taxable"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="track_inventory",
            field=models.BooleanField(
                default=True, help_text="Track stock levels for this product"
            ),
        ),
    ]
