# Generated by Django 5.0.3 on 2025-06-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_product_track_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="alert_low_stock",
            field=models.BooleanField(
                default=True, help_text="Send alerts when stock is low"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="allow_backorder",
            field=models.BooleanField(
                default=False, help_text="Allow ordering more than available stock"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this product is active and visible to customers",
            ),
        ),
    ]
