# Generated by Django 5.0.3 on 2025-06-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_alert_low_stock_product_allow_backorder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#6c757d", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="Product brand or manufacturer",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in centimeters",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length in centimeters",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Product weight in kilograms",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in centimeters",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for categorizing products",
                to="inventory.producttag",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary supplier for this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.supplier",
            ),
        ),
    ]
