# Generated by Django 5.0.3 on 2025-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_producttag_supplier_product_brand_product_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams (g)"),
                    ("kg", "Kilograms (kg)"),
                    ("lb", "Pounds (lb)"),
                    ("oz", "Ounces (oz)"),
                ],
                default="kg",
                help_text="Unit of measurement for weight",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Product weight",
                max_digits=10,
                null=True,
            ),
        ),
    ]
